// Code generated by Kitex v0.3.1. DO NOT EDIT.
package segmentservice

import (
	"github.com/cloudwego/kitex/server"
	"segmenter/idl/kitex_gen/segmenter_demo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler segmenter_demo.SegmentService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
